import type { AnalystFieldCatalog, AnalystFieldDefinition } from "./analystAdapterCore";
import type { KnowledgeValueType } from "../types/universalKnowledge";

const field = (
  source: "AG" | "ES" | "UI" | "SYSTEM",
  valueType?: KnowledgeValueType,
  objectType?: string,
  title?: string,
): AnalystFieldDefinition => ({ source, valueType, objectType, title });

/**
 * Browser-ready catalogue compiled from company+transport_format+*.yaml.
 * The transport API can inject a newer catalogue through adapter options;
 * these defaults keep the prototype deterministic when YAML is not shipped.
 */
export const DEFAULT_ANALYST_FIELD_CATALOG: AnalystFieldCatalog = {
  generalInfo: {
    shortName: field("ES", "string", undefined, "Краткое наименование"),
    name: field("ES", "string", undefined, "Полное наименование"),
    inn: field("ES", "string", undefined, "ИНН"),
    ogrn: field("ES", "string", undefined, "ОГРН"),
    kpp: field("ES", "string", undefined, "КПП"),
    legalAddress: field("ES", "text", undefined, "Юридический адрес"),
    foundingDate: field("ES", "date", undefined, "Дата регистрации"),
    industry: field("ES", "string", undefined, "Отрасль"),
    okved: field("ES", "string", undefined, "Основной ОКВЭД"),
    additionalOkved: field("ES", "array", undefined, "Дополнительные ОКВЭД"),
    capitals: field("ES", "string", undefined, "Уставный капитал"),
    taxRegime: field("ES", "string", undefined, "Налоговый режим"),
    description: field("AG", "text", undefined, "Описание компании"),
    geoOfOperations: field("AG", "text", undefined, "География деятельности"),
    naturalTechFactors: field("AG", "text", undefined, "Природные и техногенные факторы"),
    seasonality: field("AG", "text", undefined, "Сезонность"),
    goals: field("AG", "array", undefined, "Стратегические цели"),
    keyInvestProjects: field("AG", "array", undefined, "Инвестиционные проекты"),
    keyManager: field("AG", "array", "keyManager", "Ключевые менеджеры"),
    keyManagers: field("AG", "array", "keyManager", "Ключевые менеджеры"),
    extra: field("UI", "array", "extra", "Дополнительные сведения"),
    extras: field("UI", "array", "extra", "Дополнительные сведения"),
  },
  orgStructure: {
    personnelTotal: field("ES", "text", undefined, "Численность сотрудников"),
    founder: field("ES", "array", "founder", "Учредители"),
    founders: field("ES", "array", "founder", "Учредители"),
    director: field("ES", "array", "director", "Руководители"),
    directors: field("ES", "array", "director", "Руководители"),
    directorDisqualified: field("ES", "array", "directorDisqualified", "Дисквалифицированные лица"),
    subsidiary: field("ES", "array", "subsidiary", "Дочерние компании"),
    subsidiaries: field("ES", "array", "subsidiary", "Дочерние компании"),
    branch: field("ES", "array", "branch", "Филиалы"),
    branches: field("ES", "array", "branch", "Филиалы"),
    branchesCountries: field("ES", "array", "branchesCountries", "Филиалы по странам"),
    keyManager: field("ES", "array", "keyManager", "Ключевые менеджеры"),
    keyManagers: field("ES", "array", "keyManager", "Ключевые менеджеры"),
    extra: field("UI", "array", "extra", "Дополнительные сведения"),
    extras: field("UI", "array", "extra", "Дополнительные сведения"),
  },
  financialProfile: {
    nonbankRevenue: field("ES", "string", undefined, "Выручка небанковского бизнеса"),
    operatingIncome: field("ES", "string", undefined, "Операционный доход"),
    taxDebt: field("ES", "array", "taxDebt", "Налоговая задолженность"),
    receivable: field("ES", "array", "receivable", "Основные дебиторы"),
    receivablesTop20: field("ES", "array", "receivable", "Основные дебиторы"),
    extra: field("UI", "array", "extra", "Дополнительные сведения"),
    extras: field("UI", "array", "extra", "Дополнительные сведения"),
  },
  regulatoryProfile: {
    status: field("ES", "string", undefined, "Статус компании"),
    license: field("ES", "array", "license", "Лицензии"),
    licensesFinancial: field("ES", "array", "license", "Финансовые лицензии"),
    rnpRecord: field("ES", "array", "rnpRecord", "Реестр недобросовестных поставщиков"),
    rnpStatus: field("ES", "array", "rnpRecord", "Реестр недобросовестных поставщиков"),
    regulator: field("ES", "array", "regulator", "Регуляторы"),
    regulators: field("ES", "array", "regulator", "Регуляторы"),
    enforcementTotal: field("ES", "object", "enforcementTotal", "Исполнительные производства"),
    arbitrationTotal: field("ES", "object", "arbitrationTotal", "Арбитражные дела"),
    extra: field("UI", "array", "extra", "Дополнительные сведения"),
    extras: field("UI", "array", "extra", "Дополнительные сведения"),
  },
  keyManager: {
    name: field("AG", "string", undefined, "ФИО"),
    role: field("AG", "string", undefined, "Должность"),
    responsibilities: field("AG", "text", undefined, "Зона ответственности"),
    level: field("AG", "string", undefined, "Уровень в иерархии"),
  },
  founder: {
    restricted: field("ES", "boolean", undefined, "Доступ ограничен"),
    name: field("ES", "string", undefined, "Наименование"),
    inn: field("ES", "string", undefined, "ИНН"),
    ogrn: field("ES", "string", undefined, "ОГРН"),
    percent: field("ES", "number", undefined, "Доля, %"),
    active: field("ES", "boolean", undefined, "Действующий учредитель"),
    status: field("ES", "string", undefined, "Статус"),
  },
  director: {
    name: field("ES", "string", undefined, "ФИО"),
    position: field("ES", "string", undefined, "Должность"),
    isLegalEntity: field("ES", "boolean", undefined, "Юридическое лицо"),
    effectiveDate: field("ES", "date", undefined, "Актуально с"),
    status: field("ES", "string", undefined, "Статус"),
    fnsRestricted: field("ES", "boolean", undefined, "Доступ ФНС ограничен"),
  },
  directorDisqualified: {
    name: field("ES", "string", undefined, "ФИО"),
    startDate: field("ES", "date", undefined, "Дата начала"),
    endDate: field("ES", "date", undefined, "Дата окончания"),
    reason: field("ES", "text", undefined, "Основание"),
    courtDecision: field("ES", "text", undefined, "Судебное решение"),
  },
  subsidiary: {
    inn: field("ES", "string", undefined, "ИНН"),
    ogrn: field("ES", "string", undefined, "ОГРН"),
    name: field("ES", "string", undefined, "Наименование"),
    share: field("ES", "number", undefined, "Доля, %"),
    active: field("ES", "boolean", undefined, "Действующая"),
    status: field("ES", "string", undefined, "Статус"),
  },
  branch: {
    name: field("ES", "string", undefined, "Наименование"),
    address: field("ES", "text", undefined, "Адрес"),
    type: field("ES", "string", undefined, "Тип"),
    status: field("ES", "string", undefined, "Статус"),
    city: field("ES", "string", undefined, "Город"),
  },
  branchesCountries: {
    country: field("ES", "string", undefined, "Страна"),
    count: field("ES", "number", undefined, "Количество филиалов"),
  },
  receivable: {
    counterparty: field("ES", "string", undefined, "Контрагент"),
    amount: field("ES", "number", undefined, "Сумма"),
    share: field("ES", "number", undefined, "Доля"),
    dueDate: field("ES", "date", undefined, "Срок погашения"),
  },
  taxDebt: {
    debtType: field("AG", "string", undefined, "Тип задолженности"),
    amount: field("AG", "number", undefined, "Сумма задолженности"),
    count: field("AG", "number", undefined, "Количество"),
    asOfDate: field("AG", "date", undefined, "Дата актуальности"),
  },
  license: {
    number: field("ES", "string", undefined, "Номер лицензии"),
    expiryDate: field("ES", "date", undefined, "Действует до"),
    issuingAuthority: field("ES", "text", undefined, "Лицензирующий орган"),
    activityType: field("ES", "text", undefined, "Вид деятельности"),
  },
  rnpRecord: {
    rnpId: field("ES", "string", undefined, "Идентификатор РНП"),
    registrationNumber: field("ES", "string", undefined, "Регистрационный номер"),
    inclusionDate: field("ES", "date", undefined, "Дата включения"),
    exclusionDate: field("ES", "date", undefined, "Дата исключения"),
    inclusionReason: field("ES", "text", undefined, "Причина включения"),
    decisionBody: field("ES", "text", undefined, "Орган, принявший решение"),
    founderViolation: field("ES", "array", "founderViolation", "Связанные учредители"),
  },
  founderViolation: {
    inn: field("ES", "string", undefined, "ИНН"),
    ogrn: field("ES", "string", undefined, "ОГРН"),
    name: field("ES", "string", undefined, "Наименование"),
  },
  regulator: {
    department: field("ES", "text", undefined, "Ведомство"),
    lawAct: field("ES", "text", undefined, "Нормативный акт"),
  },
  enforcementTotal: {
    totalCount: field("ES", "number", undefined, "Общее количество"),
    totalSum: field("ES", "number", undefined, "Общая сумма"),
    enforcementBreakdown: field("ES", "array", "enforcementBreakdown", "Детализация"),
  },
  arbitrationTotal: {
    totalCount: field("ES", "number", undefined, "Общее количество"),
    totalSum: field("ES", "number", undefined, "Общая сумма"),
    arbitrationBreakdown: field("ES", "array", "arbitrationBreakdown", "Детализация"),
  },
  enforcementBreakdown: {
    type: field("ES", "string", undefined, "Тип"),
    count: field("ES", "number", undefined, "Количество"),
    sum: field("ES", "number", undefined, "Сумма"),
  },
  arbitrationBreakdown: {
    type: field("ES", "string", undefined, "Тип"),
    count: field("ES", "number", undefined, "Количество"),
    sum: field("ES", "number", undefined, "Сумма"),
  },
  extra: {
    key: field("UI", "string", undefined, "Ключ"),
    value: field("UI", "string", undefined, "Значение"),
    description: field("UI", "text", undefined, "Описание"),
  },
};
